import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

class AppTheme {
  const AppTheme._();

  static ThemeData get lightTheme => FlexColorScheme.light(
    scheme: FlexScheme.tealM3,
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 3,
    appBarStyle: FlexAppBarStyle.material,
    appBarOpacity: 0.95,
    transparentStatusBar: true,
    tabBarStyle: FlexTabBarStyle.flutterDefault,
    tooltipsMatchBackground: false,
    useMaterial3: true,
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepPrimary: true,
    ),
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      blendOnColors: true,
      blendTextTheme: true,
      cardRadius: 20,
      chipRadius: 12,
      dialogRadius: 24,
      inputDecoratorRadius: 16,
      filledButtonRadius: 16,
      outlinedButtonRadius: 16,
      textButtonRadius: 16,
      fabRadius: 20,
      snackBarRadius: 12,
      snackBarElevation: 4,
      drawerRadius: 24,
      bottomSheetRadius: 28,
      bottomSheetModalElevation: 8,
      tooltipRadius: 8,
      tooltipWaitDuration: Duration(milliseconds: 500),
      tooltipShowDuration: Duration(seconds: 2),
      unselectedToggleIsColored: true,
      appBarScrolledUnderElevation: 2,
    ),
  ).toTheme;

  static ThemeData get darkTheme => FlexColorScheme.dark(
    scheme: FlexScheme.tealM3,
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 6,
    appBarStyle: FlexAppBarStyle.material,
    appBarOpacity: 0.90,
    transparentStatusBar: true,
    tabBarStyle: FlexTabBarStyle.flutterDefault,
    tooltipsMatchBackground: false,
    darkIsTrueBlack: true,
    useMaterial3: true,
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepPrimary: true,
      keepSecondary: true,
    ),
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      blendOnColors: true,
      blendTextTheme: true,
      cardRadius: 20,
      chipRadius: 12,
      dialogRadius: 24,
      inputDecoratorRadius: 16,
      filledButtonRadius: 16,
      outlinedButtonRadius: 16,
      textButtonRadius: 16,
      fabRadius: 20,
      snackBarRadius: 12,
      snackBarElevation: 4,
      drawerRadius: 24,
      bottomSheetRadius: 28,
      bottomSheetModalElevation: 8,
      tooltipRadius: 8,
      tooltipWaitDuration: Duration(milliseconds: 500),
      tooltipShowDuration: Duration(seconds: 2),
      unselectedToggleIsColored: true,
      appBarScrolledUnderElevation: 2,
    ),
  ).toTheme;
}
